### ISSUE TITLE
[Bug] [dinky-gateway] build kubernetesClient with wrong config

### ISSUE THREAD

**Issue by kylinmac** [DataLinkDC/dinky#2962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

kubernetesClient = DefaultKubernetesClient.fromConfig(k8sConfig.getKubeConfig());
this build method can't analyze KubeConfig like 
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://192.168.179.101:6443
  name: kubernetes
...
```
if will read config from ~/.kube/config
![14e20af2aec5e06c9ba4d1823c1107d](https://github.com/DataLinkDC/dinky/assets/74998015/45b3fd51-d8cc-4b53-97a3-e8c54252641d)

### What you expected to happen

build with right kubeconfig

### How to reproduce

debug DefaultKubernetesClient.fromConfig(k8sConfig.getKubeConfig())

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
