### ISSUE TITLE
[Bug] [Module Name] k8s  operator create flink session ha，use ingress config

### ISSUE THREAD

**Issue by soulmz** [DataLinkDC/dinky#3543]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky 不支持 k8s  operator 创建的 session ，有 ingress 的配置

<img width="1612" alt="image" src="https://github.com/DataLinkDC/dinky/assets/10662992/4c48825b-9729-429d-8e6d-02d285c6398a">

### What you expected to happen

我希望 dinky 能发现  k8s operator 创建的 flink session 集群，允许通过 ingress 域名进行作业。

### How to reproduce

我使用 flink operator on k8s 官方的示例配置，创建一个 flink session job 集群。
```yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: basic-session-deployment-only-example
  namespace: flink
spec:
  image: flink:1.17
  flinkVersion: v1_17
  ingress:
    className: "istio"
    template: "{{name}}.{{namespace}}.devops.example.com"
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1

```

### Version

1.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
