### ISSUE TITLE
[Bug] [Cluster config] Can not save pod template with volumes yaml content

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#3850]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

pod template content
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  initContainers:
   - command:
    - chown
    - -R
    - 9999:9999
    - /flink-app-data
    image: op-harbor-prod.yili.com/clouddp/alpine:20230616
    name: init-jobmanager
    volumeMounts:
    - mountPath: /flink-app-data
      name: pv-storage
  containers:
  - name: flink-main-container
    volumeMounts:
    - mountPath: /flink-app-data
      name: pv-storage
  hostAliases:
  - ip: "10.150.4.47"
    hostnames:
      - "cdhprodcm01.yili.com"
  - ip: "10.150.4.48"
    hostnames:
      - "cdhprodcm02.yili.com"
  - ip: "10.150.4.49"
    hostnames:
      - "cdhprodcm03.yili.com"
  - ip: "10.150.4.50"
    hostnames:
      - "cdhprodnm01.yili.com"
  - ip: "10.150.4.51"
    hostnames:
      - "cdhprodnm02.yili.com"
  - ip: "10.150.5.10"
    hostnames:
      - "cdhproddn01.yili.com"
  - ip: "10.150.5.11"
    hostnames:
      - "cdhproddn02.yili.com"
  - ip: "10.150.5.12"
    hostnames:
      - "cdhproddn03.yili.com"
  - ip: "10.150.5.13"
    hostnames:
      - "cdhproddn04.yili.com"
  - ip: "10.150.5.14"
    hostnames:
      - "cdhproddn05.yili.com"
  - ip: "10.150.5.15"
    hostnames:
      - "cdhproddn06.yili.com"
  - ip: "10.150.5.16"
    hostnames:
      - "cdhproddn07.yili.com"
  - ip: "10.150.5.17"
    hostnames:
      - "cdhproddn08.yili.com"
  - ip: "10.150.5.18"
    hostnames:
      - "cdhproddn09.yili.com"
  - ip: "10.150.5.19"
    hostnames:
      - "cdhproddn10.yili.com"
  - ip: "10.150.5.20"
    hostnames:
      - "cdhproddn11.yili.com"
  - ip: "10.150.5.21"
    hostnames:
      - "cdhproddn12.yili.com"
  - ip: "10.150.5.22"
    hostnames:
      - "cdhproddn13.yili.com"
  - ip: "10.150.5.23"
    hostnames:
      - "cdhproddn14.yili.com"
  - ip: "10.150.5.24"
    hostnames:
      - "cdhproddn15.yili.com"
  - ip: "10.150.5.25"
    hostnames:
      - "cdhproddn16.yili.com"
  - ip: "10.150.5.26"
    hostnames:
      - "cdhproddn17.yili.com"
  - ip: "10.150.5.27"
    hostnames:
      - "cdhproddn18.yili.com"
  - ip: "10.150.5.28"
    hostnames:
      - "cdhproddn19.yili.com"
  - ip: "10.150.5.29"
    hostnames:
      - "cdhproddn20.yili.com"
  - ip: "10.150.5.30"
    hostnames:
      - "cdhproddn21.yili.com"
  - ip: "10.150.5.31"
    hostnames:
      - "cdhproddn22.yili.com"
  - ip: "10.150.5.32"
    hostnames:
      - "cdhproddn23.yili.com"
  - ip: "10.150.5.33"
    hostnames:
      - "cdhproddn24.yili.com"
  - ip: "10.150.5.34"
    hostnames:
      - "cdhproddn25.yili.com"
  - ip: "10.150.5.35"
    hostnames:
      - "cdhproddn26.yili.com"
  - ip: "10.150.5.36"
    hostnames:
      - "cdhproddn27.yili.com"
  - ip: "10.150.5.37"
    hostnames:
      - "cdhproddn28.yili.com"
  - ip: "10.150.5.38"
    hostnames:
      - "cdhproddn29.yili.com"
  - ip: "10.150.5.39"
    hostnames:
      - "cdhproddn30.yili.com"
  - ip: "10.150.5.40"
    hostnames:
      - "cdhproddn31.yili.com"
  - ip: "10.150.5.41"
    hostnames:
      - "cdhproddn32.yili.com"
  - ip: "10.150.5.42"
    hostnames:
      - "cdhproddn33.yili.com"
  - ip: "10.150.5.43"
    hostnames:
      - "cdhproddn34.yili.com"
  - ip: "10.150.5.44"
    hostnames:
      - "cdhproddn35.yili.com"
  - ip: "10.150.5.45"
    hostnames:
      - "cdhproddn36.yili.com"
  - ip: "10.150.5.46"
    hostnames:
      - "cdhproddn37.yili.com"
  - ip: "10.150.5.47"
    hostnames:
      - "cdhproddn38.yili.com"
  - ip: "10.150.5.48"
    hostnames:
      - "cdhproddn39.yili.com"
  - ip: "10.150.5.49"
    hostnames:
      - "cdhproddn40.yili.com"
  - ip: "10.150.5.50"
    hostnames:
      - "cdhproddn41.yili.com"
  - ip: "10.150.5.51"
    hostnames:
      - "cdhproddn42.yili.com"
  - ip: "10.150.5.58"
    hostnames:
      - "cdhproddn49.yili.com"
  - ip: "10.150.5.59"
    hostnames:
      - "cdhproddn50.yili.com"
  - ip: "10.150.5.60"
    hostnames:
      - "cdhproddn51.yili.com"
  - ip: "10.150.5.61"
    hostnames:
      - "cdhproddn52.yili.com"
  - ip: "10.150.5.62"
    hostnames:
      - "cdhproddn53.yili.com"
  - ip: "10.150.5.63"
    hostnames:
      - "cdhproddn54.yili.com"
  - ip: "10.150.5.64"
    hostnames:
      - "cdhproddn55.yili.com"
  - ip: "10.150.5.65"
    hostnames:
      - "cdhproddn56.yili.com"
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pvc-flink-new
```

### What you expected to happen

save success

### How to reproduce

in cluster config , create a k8s operator cluster, in pod template paster yaml content that I paste in this issue, then save 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
