### ISSUE TITLE
[Bug] [Catalog] The create catalog statement cannot be used

### ISSUE THREAD

**Issue by chenlb** [DataLinkDC/dinky#4096]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

新建 flink sql 任务：

```sql
CREATE CATALOG my_cata WITH (
    'type' = 'paimon',
    'warehouse' = 's3://paimon/my_cata',
    's3.endpoint' = 'http://minio:9000',
    's3.access-key' = 'AAAAAAAAAAAAAAAAAAAA',
    's3.secret-key' = 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    's3.path.style.access' = 'true'
);
```

报如下错：
```log
2024-12-29 17:33:41.440 INFO  org.dinky.service.task.FlinkSqlTask(69): Initializing Flink job config...
Process Step SUBMIT_EXECUTE exit with status:FAILED
java.lang.Exception: The statements must contain at least one INSERT/CTAS/RTAS/SELECT/WITH/SHOW/DESC statement.
	at org.dinky.job.JobManager.executeSql(JobManager.java:307)
	at org.dinky.service.task.FlinkSqlTask.execute(FlinkSqlTask.java:70)
```

用界面是可以创建 paimon 的数据源，界面也可以预览数据（本地 minio docker 用 flink sql-client 生成了一些数据，）。但在 flink sql 又不无法查询，如查询 sql：
```sql
SET 'sql-client.execution.result-mode' = 'tableau';
SET 'execution.runtime-mode' = 'batch';

select id, name, created_at, updated_at, dt, hh from my_cata.tracing.traces order by created_at desc limit 10;
```

报找不到 catalog
```log
2024-12-29 18:36:50.958 INFO  org.dinky.utils.KerberosUtil(58): Simple authentication mode
Process Step SUBMIT_EXECUTE exit with status:FAILED
java.lang.Exception: SQL validation failed. From line 1, column 54 to line 1, column 76: Object 'my_cata' not found
	at org.dinky.job.JobManager.executeSql(JobManager.java:307)
	at org.dinky.service.task.FlinkSqlTask.execute(FlinkSqlTask.java:70)
```

### What you expected to happen

在 flink sql 任务中可以使用 paimon 的 catalog

### How to reproduce

我的环境说明：

### dinky 源码编译

dinky 1.2.0  tag 代码版本。

```bash
sh build-extr.sh -j jdk11 -f flink-1.20
```

手动解压 dinky-release-1.20-1.2.0.tar.gz 到 build 目录下。

### 制作 dinky 镜像

自己制作 docker （官方的 dinkydocker/dinky-standalone-server:* 镜像 pull 不了） ，生成 dinky-flink:1.2.0-1.20 镜像
```dockerfile
ARG FLINK_VERSION=1.20
ARG DINKY_VERSION=1.2.0
ARG PAIMON_VERSION=0.9.0

FROM paimon-flink:${PAIMON_VERSION}-${FLINK_VERSION} AS flink-base

FROM eclipse-temurin:11-jre-jammy

ARG FLINK_VERSION=1.20
ARG DINKY_VERSION=1.2.0
ENV FLINK_VERSION=${FLINK_VERSION}
ENV TZ='Asia/Shanghai'
ENV DINKY_HOME=/opt/dinky
ENV H2_DB=./tmp/db/h2

WORKDIR /opt/dinky/

USER root

COPY ./build/dinky-release-${FLINK_VERSION}-${DINKY_VERSION}/ /opt/dinky/
COPY --from=flink-base  /opt/flink/lib/*.jar  /opt/dinky/extends/flink${FLINK_VERSION}/flink/
RUN rm -f  /opt/dinky/extends/flink${FLINK_VERSION}/flink/flink-table-planner-loader*.jar

COPY --from=flink-base  /opt/flink/opt/flink-table-planner*.jar /opt/dinky/extends/flink${FLINK_VERSION}/flink/

RUN mkdir /opt/dinky/customJar && chmod -R 777 /opt/dinky/ && sed -i 's/-Xms512M -Xmx2048M -XX:PermSize=512M/-XX:+UseContainerSupport -XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0/g' ./bin/auto.sh

EXPOSE 8888

CMD  ./bin/auto.sh startOnPending
```

依赖的 paimon-flink 镜像(自己制作) Dockerfile，生成 paimon-flink:0.9.0-1.20 镜像
```dockerfile
FROM flink:1.20

ARG MAVEN_MIRROR="https://maven.aliyun.com/repository/public"

ARG FLINK_VERSION="1.20"
ARG PAIMAN_VERSION="0.9.0"
ARG PAIMAN_FLINK="paimon-flink"
ARG PAIMAN_FLINK_JAR="${PAIMAN_FLINK}-${FLINK_VERSION}-${PAIMAN_VERSION}.jar"
ARG PAIMAN_ACTION_JAR="${PAIMAN_FLINK}-action-${PAIMAN_VERSION}.jar"

RUN wget -O /opt/flink/lib/${PAIMAN_FLINK_JAR} \
    "${MAVEN_MIRROR}/org/apache/paimon/${PAIMAN_FLINK}-${FLINK_VERSION}/${PAIMAN_VERSION}/${PAIMAN_FLINK_JAR}"
RUN wget -O /opt/flink/lib/${PAIMAN_ACTION_JAR} \
    "${MAVEN_MIRROR}/org/apache/paimon/${PAIMAN_FLINK}-action/${PAIMAN_VERSION}/${PAIMAN_ACTION_JAR}"

ARG FLINK_SHADED_HADOOP="flink-shaded-hadoop-2-uber"
ARG FLINK_SHADED_HADOOP_VERSION="2.8.3-10.0"
ARG FLINK_SHADED_HADOOP_JAR="${FLINK_SHADED_HADOOP}-${FLINK_SHADED_HADOOP_VERSION}.jar"
RUN wget -O /opt/flink/lib/${FLINK_SHADED_HADOOP_JAR} \
    "${MAVEN_MIRROR}/org/apache/flink/${FLINK_SHADED_HADOOP}/${FLINK_SHADED_HADOOP_VERSION}/${FLINK_SHADED_HADOOP_JAR}"

ARG FLINK_CDC_POSTGRES="flink-sql-connector-postgres-cdc"
ARG FLINK_CDC_POSTGRES_VERSION="3.2.1"
ARG FLINK_CDC_POSTGRES_JAR="${FLINK_CDC_POSTGRES}-${FLINK_CDC_POSTGRES_VERSION}.jar"
RUN wget -O /opt/flink/lib/${FLINK_CDC_POSTGRES_JAR} \
    "${MAVEN_MIRROR}/org/apache/flink/${FLINK_CDC_POSTGRES}/${FLINK_CDC_POSTGRES_VERSION}/${FLINK_CDC_POSTGRES_JAR}"

ARG FLINK_CONNECTOR_KAFKA="flink-sql-connector-kafka"
ARG FLINK_CONNECTOR_KAFKA_VERSION="3.4.0-1.20"
ARG FLINK_CONNECTOR_KAFKA_JAR="${FLINK_CONNECTOR_KAFKA}-${FLINK_CONNECTOR_KAFKA_VERSION}.jar"
RUN wget -O /opt/flink/lib/${FLINK_CONNECTOR_KAFKA_JAR} \
    "${MAVEN_MIRROR}/org/apache/flink/${FLINK_CONNECTOR_KAFKA}/${FLINK_CONNECTOR_KAFKA_VERSION}/${FLINK_CONNECTOR_KAFKA_JAR}"

RUN wget -O /opt/flink/lib/commons-cli-1.9.0.jar \
    "${MAVEN_MIRROR}/commons-cli/commons-cli/1.9.0/commons-cli-1.9.0.jar"

RUN wget -O /opt/flink/lib/flink-connector-base-1.20.0.jar \
    "${MAVEN_MIRROR}/org/apache/flink/flink-connector-base/1.20.0/flink-connector-base-1.20.0.jar"


RUN wget -O /opt/flink/lib/paimon-s3-0.9.0.jar \
    "${MAVEN_MIRROR}/org/apache/paimon/paimon-s3/0.9.0/paimon-s3-0.9.0.jar"

COPY --chown=flink:flink conf/config.yaml /opt/flink/conf/

ENV TZ='Asia/Shanghai'
```

paimon-flink docker 的 flink conf/config.yaml 如下
```yaml
blob:
  server:
    port: '6124'
taskmanager:
  memory:
    process:
      size: 1728m
  bind-host: 0.0.0.0
  numberOfTaskSlots: 1
jobmanager:
  execution:
    failover-strategy: region
  rpc:
    address: jobmanager
    port: 6123
  memory:
    process:
      size: 1600m
  bind-host: 0.0.0.0
query:
  server:
    port: '6125'
rest:
  bind-address: 0.0.0.0
  address: 0.0.0.0
parallelism:
  default: 1
env:
  java:
    opts:
      all: --add-exports=java.base/sun.net.util=ALL-UNNAMED --add-exports=java.rmi/sun.rmi.registry=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
# checkpoint
# https://nightlies.apache.org/flink/flink-docs-release-1.20/zh/docs/deployment/config/#checkpoints-and-state-backends
execution:
  checkpointing:
    dir: file:///data/flink/checkpoints/
    savepoint-dir: file:///data/flink/savepoints/
    interval: 180 s
# catalog store
# https://nightlies.apache.org/flink/flink-docs-release-1.20/zh/docs/dev/table/catalogs/#catalog-store
table:
  catalog-store:
    kind: file
    file:
      path: /data/catalog/

```

### docker-compose 文件

```yaml
services:
  jobmanager:
    image: paimon-flink:0.9.0-1.20
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - /tmp/flink-data:/data
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: paimon-flink:0.9.0-1.20
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - /tmp/flink-data:/data
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10


  postgres:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=dinky
      - POSTGRES_PASSWORD=dinky
      - POSTGRES_DB=dinky
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  dinky:
    image: dinky-flink:1.2.0-1.20
    ports:
      - "8888:8888"
    volumes:
      - /tmp/dinky/customJar:/opt/dinky/customJar/
    environment:
      DB_ACTIVE: postgresql
      POSTGRES_USER: dinky
      POSTGRES_PASSWORD: dinky
      POSTGRES_ADDR: postgres:5432
      POSTGRES_DB: dinky

volumes:
  database_data:
    driver: local
```

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
